#!/usr/bin/make -f


# MAKEFILE GENERATED BY QPC
# IF YOU ARE READING THIS AND DID NOT GENERATE THIS FILE WITH QPC,
# IT PROBABLY WILL NOT WORK. DOWNLOAD QPC AND BUILD THE MAKEFILE
# YOURSELF.


# |￣￣￣￣￣￣￣￣|  
# |    make > *    |
# |＿＿＿＿＿＿＿＿|
# (\__/) || 
# (•ㅅ•) || 
# / 　 づ  

# don't mess with this, might break stuff
ifndef $(ARCH)
ARCH = amd64
endif

# change the config with CONFIG=[Debug,Release] to make
ifndef $(CONFIG)
CONFIG = Debug
endif

# edit this in your QPC script configuration/general/compiler
ifndef $(COMPILER)
COMPILER = g++
endif


# COLORS!!!


RED     =[0;31m
CYAN    =[0;36m
GREEN   =[0;32m
NC      =[0m

############################
### BEGIN BUILD TARGETS ###
###########################

ifeq (Debug,$(CONFIG))

ifeq (i386,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/client/Debug)

# SOURCE FILES:

SOURCES = ../src/core/game_entry.cpp	\
	../chocolate/src/shared/util.cpp	\
	../chocolate/src/shared/system.cpp	\
	../chocolate/src/shared/msgs.cpp	\
	../chocolate/src/shared/platform.cpp	\
	../chocolate/src/shared/console.cpp	\
	../src/game/util.cpp	\
	../src/game/player.cpp	\
	../src/game/gamesystem.cpp	\
	../src/game/inputsystem.cpp	\
	../src/game/world.cpp

#OBJECTS:

OBJECTS = ../obj/client/Debug/game_entry.o	\
	../obj/client/Debug/util.o	\
	../obj/client/Debug/system.o	\
	../obj/client/Debug/msgs.o	\
	../obj/client/Debug/platform.o	\
	../obj/client/Debug/console.o	\
	../obj/client/Debug/player.o	\
	../obj/client/Debug/gamesystem.o	\
	../obj/client/Debug/inputsystem.o	\
	../obj/client/Debug/world.o

# MACROS:

OUTNAME = client

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/client/Debug/game_entry.o: ../src/core/game_entry.cpp
	@echo '$(CYAN)Building Object ../src/core/game_entry.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/core/game_entry.cpp -o $@

../obj/client/Debug/util.o: ../src/game/util.cpp
	@echo '$(CYAN)Building Object ../src/game/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/util.cpp -o $@

../obj/client/Debug/system.o: ../chocolate/src/shared/system.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/system.cpp -o $@

../obj/client/Debug/msgs.o: ../chocolate/src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/msgs.cpp -o $@

../obj/client/Debug/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/platform.cpp -o $@

../obj/client/Debug/console.o: ../chocolate/src/shared/console.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/console.cpp -o $@

../obj/client/Debug/player.o: ../src/game/player.cpp
	@echo '$(CYAN)Building Object ../src/game/player.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/player.cpp -o $@

../obj/client/Debug/gamesystem.o: ../src/game/gamesystem.cpp
	@echo '$(CYAN)Building Object ../src/game/gamesystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/gamesystem.cpp -o $@

../obj/client/Debug/inputsystem.o: ../src/game/inputsystem.cpp
	@echo '$(CYAN)Building Object ../src/game/inputsystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/inputsystem.cpp -o $@

../obj/client/Debug/world.o: ../src/game/world.cpp
	@echo '$(CYAN)Building Object ../src/game/world.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/world.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Debug,$(CONFIG))

ifeq (amd64,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/client/Debug)

# SOURCE FILES:

SOURCES = ../src/core/game_entry.cpp	\
	../chocolate/src/shared/util.cpp	\
	../chocolate/src/shared/system.cpp	\
	../chocolate/src/shared/msgs.cpp	\
	../chocolate/src/shared/platform.cpp	\
	../chocolate/src/shared/console.cpp	\
	../src/game/util.cpp	\
	../src/game/player.cpp	\
	../src/game/gamesystem.cpp	\
	../src/game/inputsystem.cpp	\
	../src/game/world.cpp

#OBJECTS:

OBJECTS = ../obj/client/Debug/game_entry.o	\
	../obj/client/Debug/util.o	\
	../obj/client/Debug/system.o	\
	../obj/client/Debug/msgs.o	\
	../obj/client/Debug/platform.o	\
	../obj/client/Debug/console.o	\
	../obj/client/Debug/player.o	\
	../obj/client/Debug/gamesystem.o	\
	../obj/client/Debug/inputsystem.o	\
	../obj/client/Debug/world.o

# MACROS:

OUTNAME = client

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/client/Debug/game_entry.o: ../src/core/game_entry.cpp
	@echo '$(CYAN)Building Object ../src/core/game_entry.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/core/game_entry.cpp -o $@

../obj/client/Debug/util.o: ../src/game/util.cpp
	@echo '$(CYAN)Building Object ../src/game/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/util.cpp -o $@

../obj/client/Debug/system.o: ../chocolate/src/shared/system.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/system.cpp -o $@

../obj/client/Debug/msgs.o: ../chocolate/src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/msgs.cpp -o $@

../obj/client/Debug/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/platform.cpp -o $@

../obj/client/Debug/console.o: ../chocolate/src/shared/console.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/console.cpp -o $@

../obj/client/Debug/player.o: ../src/game/player.cpp
	@echo '$(CYAN)Building Object ../src/game/player.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/player.cpp -o $@

../obj/client/Debug/gamesystem.o: ../src/game/gamesystem.cpp
	@echo '$(CYAN)Building Object ../src/game/gamesystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/gamesystem.cpp -o $@

../obj/client/Debug/inputsystem.o: ../src/game/inputsystem.cpp
	@echo '$(CYAN)Building Object ../src/game/inputsystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/inputsystem.cpp -o $@

../obj/client/Debug/world.o: ../src/game/world.cpp
	@echo '$(CYAN)Building Object ../src/game/world.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/world.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Release,$(CONFIG))

ifeq (i386,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/client/Release)

# SOURCE FILES:

SOURCES = ../src/core/game_entry.cpp	\
	../chocolate/src/shared/util.cpp	\
	../chocolate/src/shared/system.cpp	\
	../chocolate/src/shared/msgs.cpp	\
	../chocolate/src/shared/platform.cpp	\
	../chocolate/src/shared/console.cpp	\
	../src/game/util.cpp	\
	../src/game/player.cpp	\
	../src/game/gamesystem.cpp	\
	../src/game/inputsystem.cpp	\
	../src/game/world.cpp

#OBJECTS:

OBJECTS = ../obj/client/Release/game_entry.o	\
	../obj/client/Release/util.o	\
	../obj/client/Release/system.o	\
	../obj/client/Release/msgs.o	\
	../obj/client/Release/platform.o	\
	../obj/client/Release/console.o	\
	../obj/client/Release/player.o	\
	../obj/client/Release/gamesystem.o	\
	../obj/client/Release/inputsystem.o	\
	../obj/client/Release/world.o

# MACROS:

OUTNAME = client

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/client/Release/game_entry.o: ../src/core/game_entry.cpp
	@echo '$(CYAN)Building Object ../src/core/game_entry.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/core/game_entry.cpp -o $@

../obj/client/Release/util.o: ../src/game/util.cpp
	@echo '$(CYAN)Building Object ../src/game/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/util.cpp -o $@

../obj/client/Release/system.o: ../chocolate/src/shared/system.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/system.cpp -o $@

../obj/client/Release/msgs.o: ../chocolate/src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/msgs.cpp -o $@

../obj/client/Release/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/platform.cpp -o $@

../obj/client/Release/console.o: ../chocolate/src/shared/console.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/console.cpp -o $@

../obj/client/Release/player.o: ../src/game/player.cpp
	@echo '$(CYAN)Building Object ../src/game/player.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/player.cpp -o $@

../obj/client/Release/gamesystem.o: ../src/game/gamesystem.cpp
	@echo '$(CYAN)Building Object ../src/game/gamesystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/gamesystem.cpp -o $@

../obj/client/Release/inputsystem.o: ../src/game/inputsystem.cpp
	@echo '$(CYAN)Building Object ../src/game/inputsystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/inputsystem.cpp -o $@

../obj/client/Release/world.o: ../src/game/world.cpp
	@echo '$(CYAN)Building Object ../src/game/world.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/world.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Release,$(CONFIG))

ifeq (amd64,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury/bin)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/client/Release)

# SOURCE FILES:

SOURCES = ../src/core/game_entry.cpp	\
	../chocolate/src/shared/util.cpp	\
	../chocolate/src/shared/system.cpp	\
	../chocolate/src/shared/msgs.cpp	\
	../chocolate/src/shared/platform.cpp	\
	../chocolate/src/shared/console.cpp	\
	../src/game/util.cpp	\
	../src/game/player.cpp	\
	../src/game/gamesystem.cpp	\
	../src/game/inputsystem.cpp	\
	../src/game/world.cpp

#OBJECTS:

OBJECTS = ../obj/client/Release/game_entry.o	\
	../obj/client/Release/util.o	\
	../obj/client/Release/system.o	\
	../obj/client/Release/msgs.o	\
	../obj/client/Release/platform.o	\
	../obj/client/Release/console.o	\
	../obj/client/Release/player.o	\
	../obj/client/Release/gamesystem.o	\
	../obj/client/Release/inputsystem.o	\
	../obj/client/Release/world.o

# MACROS:

OUTNAME = client

# TARGETS

$(addsuffix .so,$(OUTNAME)): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(CYAN)Compiling dynamic library $(OUTNAME).so$(NC)'
	@$(COMPILER) -shared -fPIC $(SOURCES)  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/client/Release/game_entry.o: ../src/core/game_entry.cpp
	@echo '$(CYAN)Building Object ../src/core/game_entry.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/core/game_entry.cpp -o $@

../obj/client/Release/util.o: ../src/game/util.cpp
	@echo '$(CYAN)Building Object ../src/game/util.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/util.cpp -o $@

../obj/client/Release/system.o: ../chocolate/src/shared/system.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/system.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/system.cpp -o $@

../obj/client/Release/msgs.o: ../chocolate/src/shared/msgs.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/msgs.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/msgs.cpp -o $@

../obj/client/Release/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/platform.cpp -o $@

../obj/client/Release/console.o: ../chocolate/src/shared/console.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/console.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../chocolate/src/shared/console.cpp -o $@

../obj/client/Release/player.o: ../src/game/player.cpp
	@echo '$(CYAN)Building Object ../src/game/player.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/player.cpp -o $@

../obj/client/Release/gamesystem.o: ../src/game/gamesystem.cpp
	@echo '$(CYAN)Building Object ../src/game/gamesystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/gamesystem.cpp -o $@

../obj/client/Release/inputsystem.o: ../src/game/inputsystem.cpp
	@echo '$(CYAN)Building Object ../src/game/inputsystem.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/inputsystem.cpp -o $@

../obj/client/Release/world.o: ../src/game/world.cpp
	@echo '$(CYAN)Building Object ../src/game/world.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -LC:\VulkanSDK\1.2.182.0/Lib -L../chocolate/lib -ldl -lSDL2 -lvulkan -lpthread -lX11 -lXxf86vm -lXrandr -lXi -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -I../src/game ../src/game/world.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif
