#!/usr/bin/make -f


# MAKEFILE GENERATED BY QPC
# IF YOU ARE READING THIS AND DID NOT GENERATE THIS FILE WITH QPC,
# IT PROBABLY WILL NOT WORK. DOWNLOAD QPC AND BUILD THE MAKEFILE
# YOURSELF.


# |￣￣￣￣￣￣￣￣|  
# |    make > *    |
# |＿＿＿＿＿＿＿＿|
# (\__/) || 
# (•ㅅ•) || 
# / 　 づ  

# don't mess with this, might break stuff
ifndef $(ARCH)
ARCH = amd64
endif

# change the config with CONFIG=[Debug,Release] to make
ifndef $(CONFIG)
CONFIG = Debug
endif

# edit this in your QPC script configuration/general/compiler
ifndef $(COMPILER)
COMPILER = g++
endif


# COLORS!!!


RED     =[0;31m
CYAN    =[0;36m
GREEN   =[0;32m
NC      =[0m

############################
### BEGIN BUILD TARGETS ###
###########################

ifeq (Debug,$(CONFIG))

ifeq (i386,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/sidury/Debug)

# SOURCE FILES:

SOURCES = ../src/gameloader.c	\
	../chocolate/src/shared/platform.cpp

#OBJECTS:

OBJECTS = ../obj/sidury/Debug/gameloader.o	\
	../obj/sidury/Debug/platform.o

# MACROS:

OUTNAME = sidury

# TARGETS

$(OUTNAME): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(GREEN)Compiling executable $(OUTNAME)$(NC)'
	@$(COMPILER) $(SOURCES)   -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/sidury/Debug/gameloader.o: ../src/gameloader.c
	@echo '$(CYAN)Building Object ../src/gameloader.c$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../src/gameloader.c -o $@

../obj/sidury/Debug/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../chocolate/src/shared/platform.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Debug,$(CONFIG))

ifeq (amd64,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/sidury/Debug)

# SOURCE FILES:

SOURCES = ../src/gameloader.c	\
	../chocolate/src/shared/platform.cpp

#OBJECTS:

OBJECTS = ../obj/sidury/Debug/gameloader.o	\
	../obj/sidury/Debug/platform.o

# MACROS:

OUTNAME = sidury

# TARGETS

$(OUTNAME): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(GREEN)Compiling executable $(OUTNAME)$(NC)'
	@$(COMPILER) $(SOURCES)   -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/sidury/Debug/gameloader.o: ../src/gameloader.c
	@echo '$(CYAN)Building Object ../src/gameloader.c$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../src/gameloader.c -o $@

../obj/sidury/Debug/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../chocolate/src/shared/platform.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Release,$(CONFIG))

ifeq (i386,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/sidury/Release)

# SOURCE FILES:

SOURCES = ../src/gameloader.c	\
	../chocolate/src/shared/platform.cpp

#OBJECTS:

OBJECTS = ../obj/sidury/Release/gameloader.o	\
	../obj/sidury/Release/platform.o

# MACROS:

OUTNAME = sidury

# TARGETS

$(OUTNAME): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(GREEN)Compiling executable $(OUTNAME)$(NC)'
	@$(COMPILER) $(SOURCES)   -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/sidury/Release/gameloader.o: ../src/gameloader.c
	@echo '$(CYAN)Building Object ../src/gameloader.c$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../src/gameloader.c -o $@

../obj/sidury/Release/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _X86_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../chocolate/src/shared/platform.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif

ifeq (Release,$(CONFIG))

ifeq (amd64,$(ARCH))

# CREATE OUT DIR
$(shell mkdir -p ../sidury)

# CREATE BUILD DIR
$(shell mkdir -p ../obj/sidury/Release)

# SOURCE FILES:

SOURCES = ../src/gameloader.c	\
	../chocolate/src/shared/platform.cpp

#OBJECTS:

OBJECTS = ../obj/sidury/Release/gameloader.o	\
	../obj/sidury/Release/platform.o

# MACROS:

OUTNAME = sidury

# TARGETS

$(OUTNAME): __PREBUILD $(OBJECTS) __PRELINK 
	@echo '$(GREEN)Compiling executable $(OUTNAME)$(NC)'
	@$(COMPILER) $(SOURCES)   -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc -o $@
	
# CLEAN TARGET:

clean:
	@echo "Cleaning objects, archives, shared objects, and dynamic libs"
	@rm -f $(wildcard *.o *.a *.so *.dll *.dylib)

.PHONY: clean __PREBUILD __PRELINK __POSTBUILD



#DEPENDENCY TREE:


../obj/sidury/Release/gameloader.o: ../src/gameloader.c
	@echo '$(CYAN)Building Object ../src/gameloader.c$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../src/gameloader.c -o $@

../obj/sidury/Release/platform.o: ../chocolate/src/shared/platform.cpp
	@echo '$(CYAN)Building Object ../chocolate/src/shared/platform.cpp$(NC)'
	@$(COMPILER) -c -fPIC  -std=c++17 -D _AMD64_ -LC:\VulkanSDK\1.2.182.0/Lib -ldl -IC:\VulkanSDK\1.2.182.0/Include -I../chocolate/inc ../chocolate/src/shared/platform.cpp -o $@


__PREBUILD:
	



__PRELINK:
	


endif

endif
